### ISSUE TITLE
What is https://huggingface.co/datasets/daishen/legal-cfm after all?

### ISSUE THREAD

**Issue by zhimin-z** [Dai-shen/LAiW#2]
There is little information about the provenance of this dataset..

**Comment by Dai-shen** [comment]
Thanks for your attention. The legal_cfm is our private dataset, and there is still some data anonymization work that is not complete (this problem may also exist in other data sets), so it has not been released yet. We will publish all the datasets used for the evaluation benchmark and more detailed information before January 15th.

**Comment by colfeng** [comment]
> There is little information about the provenance of this dataset..

In addition, you can find the name of the original source in the Main Dataset of the table in the Dataset section.

**Comment by zhimin-z** [comment]
> > There is little information about the provenance of this dataset..
> 
> In addition, you can find the name of the original source in the Main Dataset of the table in the Dataset section.

Thanks, but I still cannot find any specifications for the data source.
![image](https://github.com/Dai-shen/LAiW/assets/8592144/f2efa95a-fec3-443c-859b-aae95f77bfcc)

**Comment by colfeng** [comment]
> > > There is little information about the provenance of this dataset..
> > 
> > 
> > In addition, you can find the name of the original source in the Main Dataset of the table in the Dataset section.
> 
> Thanks, but I still cannot find any specifications for the data source. ![image](https://private-user-images.githubusercontent.com/8592144/294928305-f2efa95a-fec3-443c-859b-aae95f77bfcc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MjQxOTQsIm5iZiI6MTcwNDcyMzg5NCwicGF0aCI6Ii84NTkyMTQ0LzI5NDkyODMwNS1mMmVmYTk1YS1mZWMzLTQ0M2MtODU5Yi1hYWU5NWY3N2JmY2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDhUMTQyNDU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWM0ZjEzNGE0NjRlOTVjZmY4NWNlOTllYTBlOTYzZGU0YmU1YzU3MjY5OWI0OTkxY2Y5ZjliZWZlZTk4YjI4YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mdmgnqR8gYfHPZCY657t5QkxPVBr8bHfi-qGH9GYqH4)

You can directly use the query of the dataset to test the model and then submit the results to us for scoring.

**Comment by zhimin-z** [comment]
> > > > There is little information about the provenance of this dataset..
> > > 
> > > 
> > > In addition, you can find the name of the original source in the Main Dataset of the table in the Dataset section.
> > 
> > 
> > Thanks, but I still cannot find any specifications for the data source. ![image](https://private-user-images.githubusercontent.com/8592144/294928305-f2efa95a-fec3-443c-859b-aae95f77bfcc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MjQxOTQsIm5iZiI6MTcwNDcyMzg5NCwicGF0aCI6Ii84NTkyMTQ0LzI5NDkyODMwNS1mMmVmYTk1YS1mZWMzLTQ0M2MtODU5Yi1hYWU5NWY3N2JmY2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDhUMTQyNDU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWM0ZjEzNGE0NjRlOTVjZmY4NWNlOTllYTBlOTYzZGU0YmU1YzU3MjY5OWI0OTkxY2Y5ZjliZWZlZTk4YjI4YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mdmgnqR8gYfHPZCY657t5QkxPVBr8bHfi-qGH9GYqH4)
> 
> You can directly use the query of the dataset to test the model and then submit the results to us for scoring.

Thanks, I am more interested in the provenance of the benchmark dataset. Maybe you can tell me a bit how you formulate this dataset.

**Comment by colfeng** [comment]
> > > > > There is little information about the provenance of this dataset..
> > > > 
> > > > 
> > > > In addition, you can find the name of the original source in the Main Dataset of the table in the Dataset section.
> > > 
> > > 
> > > Thanks, but I still cannot find any specifications for the data source. ![image](https://private-user-images.githubusercontent.com/8592144/294928305-f2efa95a-fec3-443c-859b-aae95f77bfcc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MjQxOTQsIm5iZiI6MTcwNDcyMzg5NCwicGF0aCI6Ii84NTkyMTQ0LzI5NDkyODMwNS1mMmVmYTk1YS1mZWMzLTQ0M2MtODU5Yi1hYWU5NWY3N2JmY2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDhUMTQyNDU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWM0ZjEzNGE0NjRlOTVjZmY4NWNlOTllYTBlOTYzZGU0YmU1YzU3MjY5OWI0OTkxY2Y5ZjliZWZlZTk4YjI4YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mdmgnqR8gYfHPZCY657t5QkxPVBr8bHfi-qGH9GYqH4)
> > 
> > 
> > You can directly use the query of the dataset to test the model and then submit the results to us for scoring.
> 
> Thanks, I am more interested in the provenance of the benchmark dataset. Maybe you can tell me a bit how you formulate this dataset.

Thanks for your interest in our work. You can continue to follow this project, as we will release the complete paper later. The paper will provide an introduction to formulating the dataset. However, since our dataset is intended for testing purposes, we are unable to provide too many details about the formulation to avoid potential data leaks that could affect the fairness of evaluations.

**Comment by zhimin-z** [comment]
> > > > > > There is little information about the provenance of this dataset..
> > > > > 
> > > > > 
> > > > > In addition, you can find the name of the original source in the Main Dataset of the table in the Dataset section.
> > > > 
> > > > 
> > > > Thanks, but I still cannot find any specifications for the data source. ![image](https://private-user-images.githubusercontent.com/8592144/294928305-f2efa95a-fec3-443c-859b-aae95f77bfcc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MjQxOTQsIm5iZiI6MTcwNDcyMzg5NCwicGF0aCI6Ii84NTkyMTQ0LzI5NDkyODMwNS1mMmVmYTk1YS1mZWMzLTQ0M2MtODU5Yi1hYWU5NWY3N2JmY2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDhUMTQyNDU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWM0ZjEzNGE0NjRlOTVjZmY4NWNlOTllYTBlOTYzZGU0YmU1YzU3MjY5OWI0OTkxY2Y5ZjliZWZlZTk4YjI4YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mdmgnqR8gYfHPZCY657t5QkxPVBr8bHfi-qGH9GYqH4)
> > > 
> > > 
> > > You can directly use the query of the dataset to test the model and then submit the results to us for scoring.
> > 
> > 
> > Thanks, I am more interested in the provenance of the benchmark dataset. Maybe you can tell me a bit how you formulate this dataset.
> 
> Thanks for your interest in our work. You can continue to follow this project, as we will release the complete paper later. The paper will provide an introduction to formulating the dataset. However, since our dataset is intended for testing purposes, we are unable to provide too many details about the formulation to avoid potential data leaks that could affect the fairness of evaluations.

Thanks for the reply. But this is a bit weird since other datasets are traceable and mentioned clearly in the paper. CFM seems not the same case. There is no detailed information at all.

**Comment by colfeng** [comment]
> > > > > > > There is little information about the provenance of this dataset..
> > > > > > 
> > > > > > 
> > > > > > In addition, you can find the name of the original source in the Main Dataset of the table in the Dataset section.
> > > > > 
> > > > > 
> > > > > Thanks, but I still cannot find any specifications for the data source. ![image](https://private-user-images.githubusercontent.com/8592144/294928305-f2efa95a-fec3-443c-859b-aae95f77bfcc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MjQxOTQsIm5iZiI6MTcwNDcyMzg5NCwicGF0aCI6Ii84NTkyMTQ0LzI5NDkyODMwNS1mMmVmYTk1YS1mZWMzLTQ0M2MtODU5Yi1hYWU5NWY3N2JmY2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDhUMTQyNDU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWM0ZjEzNGE0NjRlOTVjZmY4NWNlOTllYTBlOTYzZGU0YmU1YzU3MjY5OWI0OTkxY2Y5ZjliZWZlZTk4YjI4YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mdmgnqR8gYfHPZCY657t5QkxPVBr8bHfi-qGH9GYqH4)
> > > > 
> > > > 
> > > > You can directly use the query of the dataset to test the model and then submit the results to us for scoring.
> > > 
> > > 
> > > Thanks, I am more interested in the provenance of the benchmark dataset. Maybe you can tell me a bit how you formulate this dataset.
> > 
> > 
> > Thanks for your interest in our work. You can continue to follow this project, as we will release the complete paper later. The paper will provide an introduction to formulating the dataset. However, since our dataset is intended for testing purposes, we are unable to provide too many details about the formulation to avoid potential data leaks that could affect the fairness of evaluations.
> 
> Thanks for the reply. But this is a bit weird since other datasets are traceable and mentioned clearly in the paper. CFM seems not the same case. There is no detailed information at all.

The CFM is based on proprietary data that has not been published. As a result, we are unable to disclose further information.
